name: Calculator CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html

      - name: Build check
        run: test -s index.html

      - name: HTML test
        run: grep -qi "<html" index.html